name: Build Docker images

on:
  push:
    branches:
      - main

jobs:
  generate-image-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    steps:
      - id: generate-version
        run: |
            version=$(date +%Y%m%d%H%M%S)  
            echo "::set-output name=version::$version"
            echo $version

  build-and-deploy:
    needs: generate-image-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          repository: ${{ github.repository }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push wagtail base image
      #   run: |
      #     version=${{needs.generate-image-version.outputs.version}}
      #     image="ghcr.io/development-group/wagtail-base:$version"
      #     latest="ghcr.io/development-group/wagtail-base:latest"
      #     docker build ./ --file ./wagtail-base.dockerfile --tag $image --tag $latest
          
      #     docker push $image
      #     docker push $latest
          
      - name: Build and push wagtail special image
        run: |
          version=${{needs.generate-image-version.outputs.version}}
          image="ghcr.io/development-group/wagtail-special:$version"
          latest="ghcr.io/development-group/wagtail-special:latest"
          docker build ./ --file ./wagtail-special.dockerfile --tag $image --tag $latest
          
          docker push $image
          docker push $latest    